// <auto-generated>
/*
 * XYO RESTful Transaction Enrichment API
 *
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Xyo.Generated.Client;
using Xyo.Generated.Logging;
using Xyo.Generated.Model;
using System.Diagnostics.CodeAnalysis;

namespace Xyo.Generated.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IEnrichmentApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        EnrichmentApiEvents Events { get; }

        /// <summary>
        /// Transaction Enrichment
        /// </summary>
        /// <remarks>
        /// Enrich a single financial transaction synchronously.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="enrichmentRequest">Transaction enrichment request payload containing payment text and ISO-3166-1 alpha-2 country code.</param>
        /// <param name="xCorrelationID">Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)</param>
        /// <param name="traceparent">Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IEnrichTransactionApiResponse"/>&gt;</returns>
        Task<IEnrichTransactionApiResponse> EnrichTransactionAsync(EnrichmentRequest enrichmentRequest, Option<Guid> xCorrelationID = default, Option<string> traceparent = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Transaction Enrichment
        /// </summary>
        /// <remarks>
        /// Enrich a single financial transaction synchronously.
        /// </remarks>
        /// <param name="enrichmentRequest">Transaction enrichment request payload containing payment text and ISO-3166-1 alpha-2 country code.</param>
        /// <param name="xCorrelationID">Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)</param>
        /// <param name="traceparent">Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IEnrichTransactionApiResponse"/>?&gt;</returns>
        Task<IEnrichTransactionApiResponse?> EnrichTransactionOrDefaultAsync(EnrichmentRequest enrichmentRequest, Option<Guid> xCorrelationID = default, Option<string> traceparent = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Transaction Enrichments
        /// </summary>
        /// <remarks>
        /// Enrich a collection of financial transactions asynchronously.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="enrichTransactionsRequestInner">Array of transaction enrichment requests (minimum 1, maximum 50,000 items) for asynchronous batch processing.</param>
        /// <param name="xApiUser">Optional identifier for the API user or tenant. (optional)</param>
        /// <param name="xCorrelationID">Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)</param>
        /// <param name="traceparent">Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IEnrichTransactionsApiResponse"/>&gt;</returns>
        Task<IEnrichTransactionsApiResponse> EnrichTransactionsAsync(List<EnrichTransactionsRequestInner> enrichTransactionsRequestInner, Option<string> xApiUser = default, Option<Guid> xCorrelationID = default, Option<string> traceparent = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Transaction Enrichments
        /// </summary>
        /// <remarks>
        /// Enrich a collection of financial transactions asynchronously.
        /// </remarks>
        /// <param name="enrichTransactionsRequestInner">Array of transaction enrichment requests (minimum 1, maximum 50,000 items) for asynchronous batch processing.</param>
        /// <param name="xApiUser">Optional identifier for the API user or tenant. (optional)</param>
        /// <param name="xCorrelationID">Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)</param>
        /// <param name="traceparent">Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IEnrichTransactionsApiResponse"/>?&gt;</returns>
        Task<IEnrichTransactionsApiResponse?> EnrichTransactionsOrDefaultAsync(List<EnrichTransactionsRequestInner> enrichTransactionsRequestInner, Option<string> xApiUser = default, Option<Guid> xCorrelationID = default, Option<string> traceparent = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Transaction Enrichments Status
        /// </summary>
        /// <remarks>
        /// Get the status of an asynchronous bulk enrichment job.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique identifier of the asynchronous bulk enrichment job.</param>
        /// <param name="xApiUser">Optional identifier for the API user or tenant. (optional)</param>
        /// <param name="xCorrelationID">Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)</param>
        /// <param name="traceparent">Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetEnrichmentStatusApiResponse"/>&gt;</returns>
        Task<IGetEnrichmentStatusApiResponse> GetEnrichmentStatusAsync(string id, Option<string> xApiUser = default, Option<Guid> xCorrelationID = default, Option<string> traceparent = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Transaction Enrichments Status
        /// </summary>
        /// <remarks>
        /// Get the status of an asynchronous bulk enrichment job.
        /// </remarks>
        /// <param name="id">The unique identifier of the asynchronous bulk enrichment job.</param>
        /// <param name="xApiUser">Optional identifier for the API user or tenant. (optional)</param>
        /// <param name="xCorrelationID">Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)</param>
        /// <param name="traceparent">Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetEnrichmentStatusApiResponse"/>?&gt;</returns>
        Task<IGetEnrichmentStatusApiResponse?> GetEnrichmentStatusOrDefaultAsync(string id, Option<string> xApiUser = default, Option<Guid> xCorrelationID = default, Option<string> traceparent = default, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IEnrichTransactionApiResponse"/>
    /// </summary>
    public interface IEnrichTransactionApiResponse : Xyo.Generated.Client.IApiResponse, IOk<Xyo.Generated.Model.EnrichmentResponse?>, ITooManyRequests<Xyo.Generated.Model.ErrorResponse?>, IHttpStatusCode3XX<Xyo.Generated.Model.ErrorResponse?>, IHttpStatusCode4XX<Xyo.Generated.Model.ErrorResponse?>, IHttpStatusCode5XX<Xyo.Generated.Model.ErrorResponse?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 429 TooManyRequests
        /// </summary>
        /// <returns></returns>
        bool IsTooManyRequests { get; }

        /// <summary>
        /// Returns true if the response is 3XX HttpStatusCode3XX
        /// </summary>
        /// <returns></returns>
        bool IsHttpStatusCode3XX { get; }

        /// <summary>
        /// Returns true if the response is 4XX HttpStatusCode4XX
        /// </summary>
        /// <returns></returns>
        bool IsHttpStatusCode4XX { get; }

        /// <summary>
        /// Returns true if the response is 5XX HttpStatusCode5XX
        /// </summary>
        /// <returns></returns>
        bool IsHttpStatusCode5XX { get; }
    }

    /// <summary>
    /// The <see cref="IEnrichTransactionsApiResponse"/>
    /// </summary>
    public interface IEnrichTransactionsApiResponse : Xyo.Generated.Client.IApiResponse, IOk<Xyo.Generated.Model.EnrichTransactionCollectionResponse?>, ITooManyRequests<Xyo.Generated.Model.ErrorResponse?>, IHttpStatusCode3XX<Xyo.Generated.Model.ErrorResponse?>, IHttpStatusCode4XX<Xyo.Generated.Model.ErrorResponse?>, IHttpStatusCode5XX<Xyo.Generated.Model.ErrorResponse?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 429 TooManyRequests
        /// </summary>
        /// <returns></returns>
        bool IsTooManyRequests { get; }

        /// <summary>
        /// Returns true if the response is 3XX HttpStatusCode3XX
        /// </summary>
        /// <returns></returns>
        bool IsHttpStatusCode3XX { get; }

        /// <summary>
        /// Returns true if the response is 4XX HttpStatusCode4XX
        /// </summary>
        /// <returns></returns>
        bool IsHttpStatusCode4XX { get; }

        /// <summary>
        /// Returns true if the response is 5XX HttpStatusCode5XX
        /// </summary>
        /// <returns></returns>
        bool IsHttpStatusCode5XX { get; }
    }

    /// <summary>
    /// The <see cref="IGetEnrichmentStatusApiResponse"/>
    /// </summary>
    public interface IGetEnrichmentStatusApiResponse : Xyo.Generated.Client.IApiResponse, IOk<Xyo.Generated.Model.EnrichmentCollectionStatusResponse?>, ITooManyRequests<Xyo.Generated.Model.ErrorResponse?>, IHttpStatusCode3XX<Xyo.Generated.Model.ErrorResponse?>, IHttpStatusCode4XX<Xyo.Generated.Model.ErrorResponse?>, IHttpStatusCode5XX<Xyo.Generated.Model.ErrorResponse?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 429 TooManyRequests
        /// </summary>
        /// <returns></returns>
        bool IsTooManyRequests { get; }

        /// <summary>
        /// Returns true if the response is 3XX HttpStatusCode3XX
        /// </summary>
        /// <returns></returns>
        bool IsHttpStatusCode3XX { get; }

        /// <summary>
        /// Returns true if the response is 4XX HttpStatusCode4XX
        /// </summary>
        /// <returns></returns>
        bool IsHttpStatusCode4XX { get; }

        /// <summary>
        /// Returns true if the response is 5XX HttpStatusCode5XX
        /// </summary>
        /// <returns></returns>
        bool IsHttpStatusCode5XX { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class EnrichmentApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnEnrichTransaction;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorEnrichTransaction;

        internal void ExecuteOnEnrichTransaction(EnrichmentApi.EnrichTransactionApiResponse apiResponse)
        {
            OnEnrichTransaction?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorEnrichTransaction(Exception exception)
        {
            OnErrorEnrichTransaction?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnEnrichTransactions;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorEnrichTransactions;

        internal void ExecuteOnEnrichTransactions(EnrichmentApi.EnrichTransactionsApiResponse apiResponse)
        {
            OnEnrichTransactions?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorEnrichTransactions(Exception exception)
        {
            OnErrorEnrichTransactions?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnGetEnrichmentStatus;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorGetEnrichmentStatus;

        internal void ExecuteOnGetEnrichmentStatus(EnrichmentApi.GetEnrichmentStatusApiResponse apiResponse)
        {
            OnGetEnrichmentStatus?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorGetEnrichmentStatus(Exception exception)
        {
            OnErrorGetEnrichmentStatus?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class EnrichmentApi : IEnrichmentApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<EnrichmentApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public EnrichmentApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="BearerToken"/>
        /// </summary>
        public TokenProvider<BearerToken> BearerTokenProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="EnrichmentApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EnrichmentApi(ILogger<EnrichmentApi> logger, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, EnrichmentApiEvents enrichmentApiEvents,
            TokenProvider<BearerToken> bearerTokenProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            Logger = logger;
            HttpClient = httpClient;
            Events = enrichmentApiEvents;
            BearerTokenProvider = bearerTokenProvider;
        }

        partial void FormatEnrichTransaction(EnrichmentRequest enrichmentRequest, ref Option<Guid> xCorrelationID, ref Option<string> traceparent);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="enrichmentRequest"></param>
        /// <param name="traceparent"></param>
        /// <returns></returns>
        private void ValidateEnrichTransaction(EnrichmentRequest enrichmentRequest, Option<string> traceparent)
        {
            if (enrichmentRequest == null)
                throw new ArgumentNullException(nameof(enrichmentRequest));

            if (traceparent.IsSet && traceparent.Value == null)
                throw new ArgumentNullException(nameof(traceparent));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="enrichmentRequest"></param>
        /// <param name="xCorrelationID"></param>
        /// <param name="traceparent"></param>
        private void AfterEnrichTransactionDefaultImplementation(IEnrichTransactionApiResponse apiResponseLocalVar, EnrichmentRequest enrichmentRequest, Option<Guid> xCorrelationID, Option<string> traceparent)
        {
            bool suppressDefaultLog = false;
            AfterEnrichTransaction(ref suppressDefaultLog, apiResponseLocalVar, enrichmentRequest, xCorrelationID, traceparent);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="enrichmentRequest"></param>
        /// <param name="xCorrelationID"></param>
        /// <param name="traceparent"></param>
        partial void AfterEnrichTransaction(ref bool suppressDefaultLog, IEnrichTransactionApiResponse apiResponseLocalVar, EnrichmentRequest enrichmentRequest, Option<Guid> xCorrelationID, Option<string> traceparent);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="enrichmentRequest"></param>
        /// <param name="xCorrelationID"></param>
        /// <param name="traceparent"></param>
        private void OnErrorEnrichTransactionDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, EnrichmentRequest enrichmentRequest, Option<Guid> xCorrelationID, Option<string> traceparent)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorEnrichTransaction(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, enrichmentRequest, xCorrelationID, traceparent);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="enrichmentRequest"></param>
        /// <param name="xCorrelationID"></param>
        /// <param name="traceparent"></param>
        partial void OnErrorEnrichTransaction(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, EnrichmentRequest enrichmentRequest, Option<Guid> xCorrelationID, Option<string> traceparent);

        /// <summary>
        /// Transaction Enrichment Enrich a single financial transaction synchronously.
        /// </summary>
        /// <param name="enrichmentRequest">Transaction enrichment request payload containing payment text and ISO-3166-1 alpha-2 country code.</param>
        /// <param name="xCorrelationID">Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)</param>
        /// <param name="traceparent">Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IEnrichTransactionApiResponse"/>&gt;</returns>
        public async Task<IEnrichTransactionApiResponse?> EnrichTransactionOrDefaultAsync(EnrichmentRequest enrichmentRequest, Option<Guid> xCorrelationID = default, Option<string> traceparent = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await EnrichTransactionAsync(enrichmentRequest, xCorrelationID, traceparent, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Transaction Enrichment Enrich a single financial transaction synchronously.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="enrichmentRequest">Transaction enrichment request payload containing payment text and ISO-3166-1 alpha-2 country code.</param>
        /// <param name="xCorrelationID">Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)</param>
        /// <param name="traceparent">Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IEnrichTransactionApiResponse"/>&gt;</returns>
        public async Task<IEnrichTransactionApiResponse> EnrichTransactionAsync(EnrichmentRequest enrichmentRequest, Option<Guid> xCorrelationID = default, Option<string> traceparent = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateEnrichTransaction(enrichmentRequest, traceparent);

                FormatEnrichTransaction(enrichmentRequest, ref xCorrelationID, ref traceparent);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/v1/ai/finance/enrichment/transaction"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/v1/ai/finance/enrichment/transaction");

                    httpRequestMessageLocalVar.Content = (enrichmentRequest as object) is Xyo.Generated.Client.FileParameter fileParameterLocalVar
                        ? httpRequestMessageLocalVar.Content = new StreamContent(fileParameterLocalVar.Content)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(enrichmentRequest, _jsonSerializerOptions));

                    if (xCorrelationID.IsSet)
                    {
                      // Set client side default value of Header Param "X-Correlation-ID".                    
                      if (ClientUtils.IsContentHeader("X-Correlation-ID"))
                      {
                          httpRequestMessageLocalVar.Content?.Headers.Add("X-Correlation-ID", ClientUtils.ParameterToString(xCorrelationID.Value));
                      }
                      else
                      {
                          httpRequestMessageLocalVar.Headers.Add("X-Correlation-ID", ClientUtils.ParameterToString(xCorrelationID.Value));
                      }
                    }

                    if (traceparent.IsSet)
                    {
                      // Set client side default value of Header Param "traceparent".                    
                      if (ClientUtils.IsContentHeader("traceparent"))
                      {
                          httpRequestMessageLocalVar.Content?.Headers.Add("traceparent", ClientUtils.ParameterToString(traceparent.Value));
                      }
                      else
                      {
                          httpRequestMessageLocalVar.Headers.Add("traceparent", ClientUtils.ParameterToString(traceparent.Value));
                      }
                    }

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        EnrichTransactionApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/v1/ai/finance/enrichment/transaction", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterEnrichTransactionDefaultImplementation(apiResponseLocalVar, enrichmentRequest, xCorrelationID, traceparent);

                        Events.ExecuteOnEnrichTransaction(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorEnrichTransactionDefaultImplementation(e, "/v1/ai/finance/enrichment/transaction", uriBuilderLocalVar.Path, enrichmentRequest, xCorrelationID, traceparent);
                Events.ExecuteOnErrorEnrichTransaction(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="EnrichTransactionApiResponse"/>
        /// </summary>
        public partial class EnrichTransactionApiResponse : Xyo.Generated.Client.ApiResponse, IEnrichTransactionApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<EnrichmentApi> Logger { get; }

            /// <summary>
            /// The <see cref="EnrichTransactionApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public EnrichTransactionApiResponse(ILogger<EnrichmentApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="EnrichTransactionApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public EnrichTransactionApiResponse(ILogger<EnrichmentApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public Xyo.Generated.Model.EnrichmentResponse? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<Xyo.Generated.Model.EnrichmentResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out Xyo.Generated.Model.EnrichmentResponse? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public bool IsTooManyRequests => 429 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public Xyo.Generated.Model.ErrorResponse? TooManyRequests()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsTooManyRequests
                    ? System.Text.Json.JsonSerializer.Deserialize<Xyo.Generated.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryTooManyRequests([NotNullWhen(true)]out Xyo.Generated.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = TooManyRequests();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)429);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 3XX HttpStatusCode3XX
            /// </summary>
            /// <returns></returns>
            public bool IsHttpStatusCode3XX
            {
                get
                {
                    int statusCode = (int)StatusCode;
                    return 300 >= statusCode && 399 <= statusCode;
                }
            }

            /// <summary>
            /// Deserializes the response if the response is 3XX HttpStatusCode3XX
            /// </summary>
            /// <returns></returns>
            public Xyo.Generated.Model.ErrorResponse? HttpStatusCode3XX()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsHttpStatusCode3XX
                    ? System.Text.Json.JsonSerializer.Deserialize<Xyo.Generated.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 3XX HttpStatusCode3XX and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryHttpStatusCode3XX([NotNullWhen(true)]out Xyo.Generated.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = HttpStatusCode3XX();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)3);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 4XX HttpStatusCode4XX
            /// </summary>
            /// <returns></returns>
            public bool IsHttpStatusCode4XX
            {
                get
                {
                    int statusCode = (int)StatusCode;
                    return 400 >= statusCode && 499 <= statusCode;
                }
            }

            /// <summary>
            /// Deserializes the response if the response is 4XX HttpStatusCode4XX
            /// </summary>
            /// <returns></returns>
            public Xyo.Generated.Model.ErrorResponse? HttpStatusCode4XX()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsHttpStatusCode4XX
                    ? System.Text.Json.JsonSerializer.Deserialize<Xyo.Generated.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 4XX HttpStatusCode4XX and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryHttpStatusCode4XX([NotNullWhen(true)]out Xyo.Generated.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = HttpStatusCode4XX();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)4);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 5XX HttpStatusCode5XX
            /// </summary>
            /// <returns></returns>
            public bool IsHttpStatusCode5XX
            {
                get
                {
                    int statusCode = (int)StatusCode;
                    return 500 >= statusCode && 599 <= statusCode;
                }
            }

            /// <summary>
            /// Deserializes the response if the response is 5XX HttpStatusCode5XX
            /// </summary>
            /// <returns></returns>
            public Xyo.Generated.Model.ErrorResponse? HttpStatusCode5XX()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsHttpStatusCode5XX
                    ? System.Text.Json.JsonSerializer.Deserialize<Xyo.Generated.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 5XX HttpStatusCode5XX and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryHttpStatusCode5XX([NotNullWhen(true)]out Xyo.Generated.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = HttpStatusCode5XX();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)5);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatEnrichTransactions(List<EnrichTransactionsRequestInner> enrichTransactionsRequestInner, ref Option<string> xApiUser, ref Option<Guid> xCorrelationID, ref Option<string> traceparent);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="enrichTransactionsRequestInner"></param>
        /// <param name="xApiUser"></param>
        /// <param name="traceparent"></param>
        /// <returns></returns>
        private void ValidateEnrichTransactions(List<EnrichTransactionsRequestInner> enrichTransactionsRequestInner, Option<string> xApiUser, Option<string> traceparent)
        {
            if (enrichTransactionsRequestInner == null)
                throw new ArgumentNullException(nameof(enrichTransactionsRequestInner));

            if (xApiUser.IsSet && xApiUser.Value == null)
                throw new ArgumentNullException(nameof(xApiUser));

            if (traceparent.IsSet && traceparent.Value == null)
                throw new ArgumentNullException(nameof(traceparent));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="enrichTransactionsRequestInner"></param>
        /// <param name="xApiUser"></param>
        /// <param name="xCorrelationID"></param>
        /// <param name="traceparent"></param>
        private void AfterEnrichTransactionsDefaultImplementation(IEnrichTransactionsApiResponse apiResponseLocalVar, List<EnrichTransactionsRequestInner> enrichTransactionsRequestInner, Option<string> xApiUser, Option<Guid> xCorrelationID, Option<string> traceparent)
        {
            bool suppressDefaultLog = false;
            AfterEnrichTransactions(ref suppressDefaultLog, apiResponseLocalVar, enrichTransactionsRequestInner, xApiUser, xCorrelationID, traceparent);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="enrichTransactionsRequestInner"></param>
        /// <param name="xApiUser"></param>
        /// <param name="xCorrelationID"></param>
        /// <param name="traceparent"></param>
        partial void AfterEnrichTransactions(ref bool suppressDefaultLog, IEnrichTransactionsApiResponse apiResponseLocalVar, List<EnrichTransactionsRequestInner> enrichTransactionsRequestInner, Option<string> xApiUser, Option<Guid> xCorrelationID, Option<string> traceparent);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="enrichTransactionsRequestInner"></param>
        /// <param name="xApiUser"></param>
        /// <param name="xCorrelationID"></param>
        /// <param name="traceparent"></param>
        private void OnErrorEnrichTransactionsDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, List<EnrichTransactionsRequestInner> enrichTransactionsRequestInner, Option<string> xApiUser, Option<Guid> xCorrelationID, Option<string> traceparent)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorEnrichTransactions(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, enrichTransactionsRequestInner, xApiUser, xCorrelationID, traceparent);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="enrichTransactionsRequestInner"></param>
        /// <param name="xApiUser"></param>
        /// <param name="xCorrelationID"></param>
        /// <param name="traceparent"></param>
        partial void OnErrorEnrichTransactions(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, List<EnrichTransactionsRequestInner> enrichTransactionsRequestInner, Option<string> xApiUser, Option<Guid> xCorrelationID, Option<string> traceparent);

        /// <summary>
        /// Transaction Enrichments Enrich a collection of financial transactions asynchronously.
        /// </summary>
        /// <param name="enrichTransactionsRequestInner">Array of transaction enrichment requests (minimum 1, maximum 50,000 items) for asynchronous batch processing.</param>
        /// <param name="xApiUser">Optional identifier for the API user or tenant. (optional)</param>
        /// <param name="xCorrelationID">Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)</param>
        /// <param name="traceparent">Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IEnrichTransactionsApiResponse"/>&gt;</returns>
        public async Task<IEnrichTransactionsApiResponse?> EnrichTransactionsOrDefaultAsync(List<EnrichTransactionsRequestInner> enrichTransactionsRequestInner, Option<string> xApiUser = default, Option<Guid> xCorrelationID = default, Option<string> traceparent = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await EnrichTransactionsAsync(enrichTransactionsRequestInner, xApiUser, xCorrelationID, traceparent, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Transaction Enrichments Enrich a collection of financial transactions asynchronously.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="enrichTransactionsRequestInner">Array of transaction enrichment requests (minimum 1, maximum 50,000 items) for asynchronous batch processing.</param>
        /// <param name="xApiUser">Optional identifier for the API user or tenant. (optional)</param>
        /// <param name="xCorrelationID">Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)</param>
        /// <param name="traceparent">Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IEnrichTransactionsApiResponse"/>&gt;</returns>
        public async Task<IEnrichTransactionsApiResponse> EnrichTransactionsAsync(List<EnrichTransactionsRequestInner> enrichTransactionsRequestInner, Option<string> xApiUser = default, Option<Guid> xCorrelationID = default, Option<string> traceparent = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateEnrichTransactions(enrichTransactionsRequestInner, xApiUser, traceparent);

                FormatEnrichTransactions(enrichTransactionsRequestInner, ref xApiUser, ref xCorrelationID, ref traceparent);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/v1/ai/finance/enrichment/transactions"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/v1/ai/finance/enrichment/transactions");

                    httpRequestMessageLocalVar.Content = (enrichTransactionsRequestInner as object) is Xyo.Generated.Client.FileParameter fileParameterLocalVar
                        ? httpRequestMessageLocalVar.Content = new StreamContent(fileParameterLocalVar.Content)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(enrichTransactionsRequestInner, _jsonSerializerOptions));

                    if (xApiUser.IsSet)
                    {
                      // Set client side default value of Header Param "x-api-user".                    
                      if (ClientUtils.IsContentHeader("x-api-user"))
                      {
                          httpRequestMessageLocalVar.Content?.Headers.Add("x-api-user", ClientUtils.ParameterToString(xApiUser.Value));
                      }
                      else
                      {
                          httpRequestMessageLocalVar.Headers.Add("x-api-user", ClientUtils.ParameterToString(xApiUser.Value));
                      }
                    }

                    if (xCorrelationID.IsSet)
                    {
                      // Set client side default value of Header Param "X-Correlation-ID".                    
                      if (ClientUtils.IsContentHeader("X-Correlation-ID"))
                      {
                          httpRequestMessageLocalVar.Content?.Headers.Add("X-Correlation-ID", ClientUtils.ParameterToString(xCorrelationID.Value));
                      }
                      else
                      {
                          httpRequestMessageLocalVar.Headers.Add("X-Correlation-ID", ClientUtils.ParameterToString(xCorrelationID.Value));
                      }
                    }

                    if (traceparent.IsSet)
                    {
                      // Set client side default value of Header Param "traceparent".                    
                      if (ClientUtils.IsContentHeader("traceparent"))
                      {
                          httpRequestMessageLocalVar.Content?.Headers.Add("traceparent", ClientUtils.ParameterToString(traceparent.Value));
                      }
                      else
                      {
                          httpRequestMessageLocalVar.Headers.Add("traceparent", ClientUtils.ParameterToString(traceparent.Value));
                      }
                    }

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        EnrichTransactionsApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/v1/ai/finance/enrichment/transactions", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterEnrichTransactionsDefaultImplementation(apiResponseLocalVar, enrichTransactionsRequestInner, xApiUser, xCorrelationID, traceparent);

                        Events.ExecuteOnEnrichTransactions(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorEnrichTransactionsDefaultImplementation(e, "/v1/ai/finance/enrichment/transactions", uriBuilderLocalVar.Path, enrichTransactionsRequestInner, xApiUser, xCorrelationID, traceparent);
                Events.ExecuteOnErrorEnrichTransactions(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="EnrichTransactionsApiResponse"/>
        /// </summary>
        public partial class EnrichTransactionsApiResponse : Xyo.Generated.Client.ApiResponse, IEnrichTransactionsApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<EnrichmentApi> Logger { get; }

            /// <summary>
            /// The <see cref="EnrichTransactionsApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public EnrichTransactionsApiResponse(ILogger<EnrichmentApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="EnrichTransactionsApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public EnrichTransactionsApiResponse(ILogger<EnrichmentApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public Xyo.Generated.Model.EnrichTransactionCollectionResponse? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<Xyo.Generated.Model.EnrichTransactionCollectionResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out Xyo.Generated.Model.EnrichTransactionCollectionResponse? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public bool IsTooManyRequests => 429 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public Xyo.Generated.Model.ErrorResponse? TooManyRequests()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsTooManyRequests
                    ? System.Text.Json.JsonSerializer.Deserialize<Xyo.Generated.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryTooManyRequests([NotNullWhen(true)]out Xyo.Generated.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = TooManyRequests();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)429);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 3XX HttpStatusCode3XX
            /// </summary>
            /// <returns></returns>
            public bool IsHttpStatusCode3XX
            {
                get
                {
                    int statusCode = (int)StatusCode;
                    return 300 >= statusCode && 399 <= statusCode;
                }
            }

            /// <summary>
            /// Deserializes the response if the response is 3XX HttpStatusCode3XX
            /// </summary>
            /// <returns></returns>
            public Xyo.Generated.Model.ErrorResponse? HttpStatusCode3XX()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsHttpStatusCode3XX
                    ? System.Text.Json.JsonSerializer.Deserialize<Xyo.Generated.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 3XX HttpStatusCode3XX and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryHttpStatusCode3XX([NotNullWhen(true)]out Xyo.Generated.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = HttpStatusCode3XX();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)3);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 4XX HttpStatusCode4XX
            /// </summary>
            /// <returns></returns>
            public bool IsHttpStatusCode4XX
            {
                get
                {
                    int statusCode = (int)StatusCode;
                    return 400 >= statusCode && 499 <= statusCode;
                }
            }

            /// <summary>
            /// Deserializes the response if the response is 4XX HttpStatusCode4XX
            /// </summary>
            /// <returns></returns>
            public Xyo.Generated.Model.ErrorResponse? HttpStatusCode4XX()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsHttpStatusCode4XX
                    ? System.Text.Json.JsonSerializer.Deserialize<Xyo.Generated.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 4XX HttpStatusCode4XX and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryHttpStatusCode4XX([NotNullWhen(true)]out Xyo.Generated.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = HttpStatusCode4XX();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)4);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 5XX HttpStatusCode5XX
            /// </summary>
            /// <returns></returns>
            public bool IsHttpStatusCode5XX
            {
                get
                {
                    int statusCode = (int)StatusCode;
                    return 500 >= statusCode && 599 <= statusCode;
                }
            }

            /// <summary>
            /// Deserializes the response if the response is 5XX HttpStatusCode5XX
            /// </summary>
            /// <returns></returns>
            public Xyo.Generated.Model.ErrorResponse? HttpStatusCode5XX()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsHttpStatusCode5XX
                    ? System.Text.Json.JsonSerializer.Deserialize<Xyo.Generated.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 5XX HttpStatusCode5XX and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryHttpStatusCode5XX([NotNullWhen(true)]out Xyo.Generated.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = HttpStatusCode5XX();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)5);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatGetEnrichmentStatus(ref string id, ref Option<string> xApiUser, ref Option<Guid> xCorrelationID, ref Option<string> traceparent);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="id"></param>
        /// <param name="xApiUser"></param>
        /// <param name="traceparent"></param>
        /// <returns></returns>
        private void ValidateGetEnrichmentStatus(string id, Option<string> xApiUser, Option<string> traceparent)
        {
            if (id == null)
                throw new ArgumentNullException(nameof(id));

            if (xApiUser.IsSet && xApiUser.Value == null)
                throw new ArgumentNullException(nameof(xApiUser));

            if (traceparent.IsSet && traceparent.Value == null)
                throw new ArgumentNullException(nameof(traceparent));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="id"></param>
        /// <param name="xApiUser"></param>
        /// <param name="xCorrelationID"></param>
        /// <param name="traceparent"></param>
        private void AfterGetEnrichmentStatusDefaultImplementation(IGetEnrichmentStatusApiResponse apiResponseLocalVar, string id, Option<string> xApiUser, Option<Guid> xCorrelationID, Option<string> traceparent)
        {
            bool suppressDefaultLog = false;
            AfterGetEnrichmentStatus(ref suppressDefaultLog, apiResponseLocalVar, id, xApiUser, xCorrelationID, traceparent);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="id"></param>
        /// <param name="xApiUser"></param>
        /// <param name="xCorrelationID"></param>
        /// <param name="traceparent"></param>
        partial void AfterGetEnrichmentStatus(ref bool suppressDefaultLog, IGetEnrichmentStatusApiResponse apiResponseLocalVar, string id, Option<string> xApiUser, Option<Guid> xCorrelationID, Option<string> traceparent);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="id"></param>
        /// <param name="xApiUser"></param>
        /// <param name="xCorrelationID"></param>
        /// <param name="traceparent"></param>
        private void OnErrorGetEnrichmentStatusDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string id, Option<string> xApiUser, Option<Guid> xCorrelationID, Option<string> traceparent)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorGetEnrichmentStatus(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, id, xApiUser, xCorrelationID, traceparent);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="id"></param>
        /// <param name="xApiUser"></param>
        /// <param name="xCorrelationID"></param>
        /// <param name="traceparent"></param>
        partial void OnErrorGetEnrichmentStatus(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string id, Option<string> xApiUser, Option<Guid> xCorrelationID, Option<string> traceparent);

        /// <summary>
        /// Transaction Enrichments Status Get the status of an asynchronous bulk enrichment job.
        /// </summary>
        /// <param name="id">The unique identifier of the asynchronous bulk enrichment job.</param>
        /// <param name="xApiUser">Optional identifier for the API user or tenant. (optional)</param>
        /// <param name="xCorrelationID">Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)</param>
        /// <param name="traceparent">Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetEnrichmentStatusApiResponse"/>&gt;</returns>
        public async Task<IGetEnrichmentStatusApiResponse?> GetEnrichmentStatusOrDefaultAsync(string id, Option<string> xApiUser = default, Option<Guid> xCorrelationID = default, Option<string> traceparent = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await GetEnrichmentStatusAsync(id, xApiUser, xCorrelationID, traceparent, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Transaction Enrichments Status Get the status of an asynchronous bulk enrichment job.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique identifier of the asynchronous bulk enrichment job.</param>
        /// <param name="xApiUser">Optional identifier for the API user or tenant. (optional)</param>
        /// <param name="xCorrelationID">Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional)</param>
        /// <param name="traceparent">Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetEnrichmentStatusApiResponse"/>&gt;</returns>
        public async Task<IGetEnrichmentStatusApiResponse> GetEnrichmentStatusAsync(string id, Option<string> xApiUser = default, Option<Guid> xCorrelationID = default, Option<string> traceparent = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateGetEnrichmentStatus(id, xApiUser, traceparent);

                FormatGetEnrichmentStatus(ref id, ref xApiUser, ref xCorrelationID, ref traceparent);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/v1/ai/finance/enrichment/status/{id}"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/v1/ai/finance/enrichment/status/{id}");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Bid%7D", Uri.EscapeDataString(id.ToString()));

                    if (xApiUser.IsSet)
                    {
                      // Set client side default value of Header Param "x-api-user".                    
                      if (ClientUtils.IsContentHeader("x-api-user"))
                      {
                          httpRequestMessageLocalVar.Content?.Headers.Add("x-api-user", ClientUtils.ParameterToString(xApiUser.Value));
                      }
                      else
                      {
                          httpRequestMessageLocalVar.Headers.Add("x-api-user", ClientUtils.ParameterToString(xApiUser.Value));
                      }
                    }

                    if (xCorrelationID.IsSet)
                    {
                      // Set client side default value of Header Param "X-Correlation-ID".                    
                      if (ClientUtils.IsContentHeader("X-Correlation-ID"))
                      {
                          httpRequestMessageLocalVar.Content?.Headers.Add("X-Correlation-ID", ClientUtils.ParameterToString(xCorrelationID.Value));
                      }
                      else
                      {
                          httpRequestMessageLocalVar.Headers.Add("X-Correlation-ID", ClientUtils.ParameterToString(xCorrelationID.Value));
                      }
                    }

                    if (traceparent.IsSet)
                    {
                      // Set client side default value of Header Param "traceparent".                    
                      if (ClientUtils.IsContentHeader("traceparent"))
                      {
                          httpRequestMessageLocalVar.Content?.Headers.Add("traceparent", ClientUtils.ParameterToString(traceparent.Value));
                      }
                      else
                      {
                          httpRequestMessageLocalVar.Headers.Add("traceparent", ClientUtils.ParameterToString(traceparent.Value));
                      }
                    }

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        GetEnrichmentStatusApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/v1/ai/finance/enrichment/status/{id}", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterGetEnrichmentStatusDefaultImplementation(apiResponseLocalVar, id, xApiUser, xCorrelationID, traceparent);

                        Events.ExecuteOnGetEnrichmentStatus(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorGetEnrichmentStatusDefaultImplementation(e, "/v1/ai/finance/enrichment/status/{id}", uriBuilderLocalVar.Path, id, xApiUser, xCorrelationID, traceparent);
                Events.ExecuteOnErrorGetEnrichmentStatus(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="GetEnrichmentStatusApiResponse"/>
        /// </summary>
        public partial class GetEnrichmentStatusApiResponse : Xyo.Generated.Client.ApiResponse, IGetEnrichmentStatusApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<EnrichmentApi> Logger { get; }

            /// <summary>
            /// The <see cref="GetEnrichmentStatusApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetEnrichmentStatusApiResponse(ILogger<EnrichmentApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="GetEnrichmentStatusApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetEnrichmentStatusApiResponse(ILogger<EnrichmentApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public Xyo.Generated.Model.EnrichmentCollectionStatusResponse? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<Xyo.Generated.Model.EnrichmentCollectionStatusResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out Xyo.Generated.Model.EnrichmentCollectionStatusResponse? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public bool IsTooManyRequests => 429 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public Xyo.Generated.Model.ErrorResponse? TooManyRequests()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsTooManyRequests
                    ? System.Text.Json.JsonSerializer.Deserialize<Xyo.Generated.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryTooManyRequests([NotNullWhen(true)]out Xyo.Generated.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = TooManyRequests();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)429);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 3XX HttpStatusCode3XX
            /// </summary>
            /// <returns></returns>
            public bool IsHttpStatusCode3XX
            {
                get
                {
                    int statusCode = (int)StatusCode;
                    return 300 >= statusCode && 399 <= statusCode;
                }
            }

            /// <summary>
            /// Deserializes the response if the response is 3XX HttpStatusCode3XX
            /// </summary>
            /// <returns></returns>
            public Xyo.Generated.Model.ErrorResponse? HttpStatusCode3XX()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsHttpStatusCode3XX
                    ? System.Text.Json.JsonSerializer.Deserialize<Xyo.Generated.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 3XX HttpStatusCode3XX and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryHttpStatusCode3XX([NotNullWhen(true)]out Xyo.Generated.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = HttpStatusCode3XX();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)3);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 4XX HttpStatusCode4XX
            /// </summary>
            /// <returns></returns>
            public bool IsHttpStatusCode4XX
            {
                get
                {
                    int statusCode = (int)StatusCode;
                    return 400 >= statusCode && 499 <= statusCode;
                }
            }

            /// <summary>
            /// Deserializes the response if the response is 4XX HttpStatusCode4XX
            /// </summary>
            /// <returns></returns>
            public Xyo.Generated.Model.ErrorResponse? HttpStatusCode4XX()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsHttpStatusCode4XX
                    ? System.Text.Json.JsonSerializer.Deserialize<Xyo.Generated.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 4XX HttpStatusCode4XX and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryHttpStatusCode4XX([NotNullWhen(true)]out Xyo.Generated.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = HttpStatusCode4XX();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)4);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 5XX HttpStatusCode5XX
            /// </summary>
            /// <returns></returns>
            public bool IsHttpStatusCode5XX
            {
                get
                {
                    int statusCode = (int)StatusCode;
                    return 500 >= statusCode && 599 <= statusCode;
                }
            }

            /// <summary>
            /// Deserializes the response if the response is 5XX HttpStatusCode5XX
            /// </summary>
            /// <returns></returns>
            public Xyo.Generated.Model.ErrorResponse? HttpStatusCode5XX()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsHttpStatusCode5XX
                    ? System.Text.Json.JsonSerializer.Deserialize<Xyo.Generated.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 5XX HttpStatusCode5XX and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryHttpStatusCode5XX([NotNullWhen(true)]out Xyo.Generated.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = HttpStatusCode5XX();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)5);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
