using System.Net;
using System.Text.Json;

namespace Xyo.Sdk.Exceptions;

/// <summary>
/// Exception thrown when the API returns an RFC 7807 problem details document (application/problem+json or application/json).
/// </summary>
public class XyoProblemDetailsException : XyoClientException
{
    /// <summary>
    /// Gets a URI reference that identifies the problem type.
    /// </summary>
    public string? Type { get; }

    /// <summary>
    /// Gets a short, human-readable summary of the problem type.
    /// </summary>
    public string? Title { get; }

    /// <summary>
    /// Gets the HTTP status code generated by the origin server for this occurrence of the problem.
    /// </summary>
    public int? Status { get; }

    /// <summary>
    /// Gets a human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    public string? Detail { get; }

    /// <summary>
    /// Gets a URI reference that identifies the specific occurrence of the problem.
    /// </summary>
    public string? Instance { get; }

    /// <summary>
    /// Gets structured field-level or category-level error details dictionary.
    /// </summary>
    public IReadOnlyDictionary<string, string[]>? Errors { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="XyoProblemDetailsException"/> class.
    /// </summary>
    public XyoProblemDetailsException(
        HttpStatusCode statusCode,
        string message,
        string? type = null,
        string? title = null,
        int? status = null,
        string? detail = null,
        string? instance = null,
        IReadOnlyDictionary<string, string[]>? errors = null,
        string? rawResponseBody = null,
        Exception? innerException = null)
        : base(statusCode, message, rawResponseBody, innerException)
    {
        Type = type;
        Title = title;
        Status = status ?? (int)statusCode;
        Detail = detail;
        Instance = instance;
        Errors = errors;
    }

    /// <summary>
    /// Attempts to parse an RFC 7807 problem details JSON payload into an <see cref="XyoProblemDetailsException"/>.
    /// </summary>
    public static XyoProblemDetailsException FromJson(HttpStatusCode statusCode, string jsonPayload, Exception? innerException = null)
    {
        try
        {
            using var doc = JsonDocument.Parse(jsonPayload);
            var root = doc.RootElement;

            string? type = root.TryGetProperty("type", out var typeProp) ? typeProp.GetString() : null;
            string? title = root.TryGetProperty("title", out var titleProp) ? titleProp.GetString() : null;
            int? status = root.TryGetProperty("status", out var statusProp) && statusProp.TryGetInt32(out var s) ? s : (int)statusCode;
            string? detail = root.TryGetProperty("detail", out var detailProp) ? detailProp.GetString() : null;
            string? instance = root.TryGetProperty("instance", out var instProp) ? instProp.GetString() : null;

            Dictionary<string, string[]>? errors = null;
            if (root.TryGetProperty("errors", out var errorsProp))
            {
                errors = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase);
                if (errorsProp.ValueKind == JsonValueKind.Object)
                {
                    foreach (var prop in errorsProp.EnumerateObject())
                    {
                        if (prop.Value.ValueKind == JsonValueKind.Array)
                        {
                            var list = new List<string>();
                            foreach (var item in prop.Value.EnumerateArray())
                            {
                                if (item.ValueKind == JsonValueKind.String)
                                {
                                    list.Add(item.GetString()!);
                                }
                            }
                            errors[prop.Name] = list.ToArray();
                        }
                        else if (prop.Value.ValueKind == JsonValueKind.String)
                        {
                            errors[prop.Name] = new[] { prop.Value.GetString()! };
                        }
                    }
                }
            }

            string formattedMessage = detail ?? title ?? $"[HTTP {(int)statusCode}] Request failed";
            return new XyoProblemDetailsException(statusCode, formattedMessage, type, title, status, detail, instance, errors, jsonPayload, innerException);
        }
        catch
        {
            string sanitized = jsonPayload.Length > 512 ? jsonPayload.Substring(0, 512) + "..." : jsonPayload;
            return new XyoProblemDetailsException(statusCode, $"[HTTP {(int)statusCode}] {sanitized}", rawResponseBody: jsonPayload, innerException: innerException);
        }
    }
}
