// <auto-generated>
/*
 * XYO RESTful Transaction Enrichment API
 *
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Xyo.Generated.Client;

namespace Xyo.Generated.Model
{
    /// <summary>
    /// RFC 7807 compliant problem details object representing an API error.
    /// </summary>
    public partial class APIError : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="APIError" /> class.
        /// </summary>
        /// <param name="type">A URI reference identifying the problem type.</param>
        /// <param name="title">A short, human-readable summary of the problem type.</param>
        /// <param name="status">The HTTP status code generated by the origin server for this occurrence of the problem.</param>
        /// <param name="detail">A human-readable explanation specific to this occurrence of the problem.</param>
        /// <param name="instance">A URI reference identifying the specific occurrence of the problem.</param>
        [JsonConstructor]
        public APIError(string type, string title, int status, string detail, string instance)
        {
            Type = type;
            Title = title;
            Status = status;
            Detail = detail;
            Instance = instance;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// A URI reference identifying the problem type.
        /// </summary>
        /// <value>A URI reference identifying the problem type.</value>
        /* <example>https://api.xyo.financial/errors/unauthorized</example> */
        [JsonPropertyName("type")]
        public string Type { get; set; }

        /// <summary>
        /// A short, human-readable summary of the problem type.
        /// </summary>
        /// <value>A short, human-readable summary of the problem type.</value>
        /* <example>Unauthorized</example> */
        [JsonPropertyName("title")]
        public string Title { get; set; }

        /// <summary>
        /// The HTTP status code generated by the origin server for this occurrence of the problem.
        /// </summary>
        /// <value>The HTTP status code generated by the origin server for this occurrence of the problem.</value>
        /* <example>401</example> */
        [JsonPropertyName("status")]
        public int Status { get; set; }

        /// <summary>
        /// A human-readable explanation specific to this occurrence of the problem.
        /// </summary>
        /// <value>A human-readable explanation specific to this occurrence of the problem.</value>
        /* <example>Invalid or expired Bearer authentication token provided.</example> */
        [JsonPropertyName("detail")]
        public string Detail { get; set; }

        /// <summary>
        /// A URI reference identifying the specific occurrence of the problem.
        /// </summary>
        /// <value>A URI reference identifying the specific occurrence of the problem.</value>
        /* <example>/v1/ai/finance/enrichment/transaction#req-9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d</example> */
        [JsonPropertyName("instance")]
        public string Instance { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class APIError {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Detail: ").Append(Detail).Append("\n");
            sb.Append("  Instance: ").Append(Instance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="APIError" />
    /// </summary>
    public partial class APIErrorJsonConverter : JsonConverter<APIError>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="APIErrorJsonConverter" /> class.
        /// </summary>
        public APIErrorJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="APIError" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override APIError Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> type = default;
            Option<string?> title = default;
            Option<int?> status = default;
            Option<string?> detail = default;
            Option<string?> instance = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            status = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "detail":
                            detail = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "instance":
                            instance = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class APIError.", nameof(type));

            if (!title.IsSet)
                throw new ArgumentException("Property is required for class APIError.", nameof(title));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class APIError.", nameof(status));

            if (!detail.IsSet)
                throw new ArgumentException("Property is required for class APIError.", nameof(detail));

            if (!instance.IsSet)
                throw new ArgumentException("Property is required for class APIError.", nameof(instance));

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class APIError.");

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class APIError.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class APIError.");

            if (detail.IsSet && detail.Value == null)
                throw new ArgumentNullException(nameof(detail), "Property is not nullable for class APIError.");

            if (instance.IsSet && instance.Value == null)
                throw new ArgumentNullException(nameof(instance), "Property is not nullable for class APIError.");

            return new APIError(type.Value!, title.Value!, status.Value!.Value!, detail.Value!, instance.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="APIError" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="aPIError"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, APIError aPIError, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, aPIError, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="APIError" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="aPIError"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, APIError aPIError, JsonSerializerOptions jsonSerializerOptions)
        {
            if (aPIError.Type == null)
                throw new ArgumentNullException(nameof(aPIError.Type), "Property is required for class APIError.");

            if (aPIError.Title == null)
                throw new ArgumentNullException(nameof(aPIError.Title), "Property is required for class APIError.");

            if (aPIError.Detail == null)
                throw new ArgumentNullException(nameof(aPIError.Detail), "Property is required for class APIError.");

            if (aPIError.Instance == null)
                throw new ArgumentNullException(nameof(aPIError.Instance), "Property is required for class APIError.");

            writer.WriteString("type", aPIError.Type);

            writer.WriteString("title", aPIError.Title);

            writer.WriteNumber("status", aPIError.Status);

            writer.WriteString("detail", aPIError.Detail);

            writer.WriteString("instance", aPIError.Instance);
        }
    }
}
