// <auto-generated>
/*
 * XYO RESTful Transaction Enrichment API
 *
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Xyo.Generated.Client;

namespace Xyo.Generated.Model
{
    /// <summary>
    /// EnrichTransactionCollectionResponse
    /// </summary>
    public partial class EnrichTransactionCollectionResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EnrichTransactionCollectionResponse" /> class.
        /// </summary>
        /// <param name="id">ID is the work ID for the enrichment request.</param>
        /// <param name="link">Link is the URL to the downloadable tar.gz results archive.</param>
        [JsonConstructor]
        public EnrichTransactionCollectionResponse(string id, string link)
        {
            Id = id;
            Link = link;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// ID is the work ID for the enrichment request.
        /// </summary>
        /// <value>ID is the work ID for the enrichment request.</value>
        /* <example>72c037df-d0d3-43ee-9470-323ff35a2e50</example> */
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Link is the URL to the downloadable tar.gz results archive.
        /// </summary>
        /// <value>Link is the URL to the downloadable tar.gz results archive.</value>
        /* <example>https://api.xyo.financial/v1/ai/finance/enrichment/download/72c037df-d0d3-43ee-9470-323ff35a2e50.tar.gz</example> */
        [JsonPropertyName("link")]
        public string Link { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EnrichTransactionCollectionResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Link: ").Append(Link).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EnrichTransactionCollectionResponse" />
    /// </summary>
    public partial class EnrichTransactionCollectionResponseJsonConverter : JsonConverter<EnrichTransactionCollectionResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="EnrichTransactionCollectionResponseJsonConverter" /> class.
        /// </summary>
        public EnrichTransactionCollectionResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="EnrichTransactionCollectionResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EnrichTransactionCollectionResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> link = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "link":
                            link = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class EnrichTransactionCollectionResponse.", nameof(id));

            if (!link.IsSet)
                throw new ArgumentException("Property is required for class EnrichTransactionCollectionResponse.", nameof(link));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class EnrichTransactionCollectionResponse.");

            if (link.IsSet && link.Value == null)
                throw new ArgumentNullException(nameof(link), "Property is not nullable for class EnrichTransactionCollectionResponse.");

            return new EnrichTransactionCollectionResponse(id.Value!, link.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="EnrichTransactionCollectionResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="enrichTransactionCollectionResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EnrichTransactionCollectionResponse enrichTransactionCollectionResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, enrichTransactionCollectionResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EnrichTransactionCollectionResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="enrichTransactionCollectionResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EnrichTransactionCollectionResponse enrichTransactionCollectionResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (enrichTransactionCollectionResponse.Id == null)
                throw new ArgumentNullException(nameof(enrichTransactionCollectionResponse.Id), "Property is required for class EnrichTransactionCollectionResponse.");

            if (enrichTransactionCollectionResponse.Link == null)
                throw new ArgumentNullException(nameof(enrichTransactionCollectionResponse.Link), "Property is required for class EnrichTransactionCollectionResponse.");

            writer.WriteString("id", enrichTransactionCollectionResponse.Id);

            writer.WriteString("link", enrichTransactionCollectionResponse.Link);
        }
    }
}
