// <auto-generated>
/*
 * XYO RESTful Transaction Enrichment API
 *
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Xyo.Generated.Client;

namespace Xyo.Generated.Model
{
    /// <summary>
    /// EnrichTransactionsRequestInner
    /// </summary>
    public partial class EnrichTransactionsRequestInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EnrichTransactionsRequestInner" /> class.
        /// </summary>
        /// <param name="content">Content is the payment description, maximum 128 characters.</param>
        /// <param name="countryCode">CountryCode is the ISO 3166-1 alpha-2 two-character country code.</param>
        [JsonConstructor]
        public EnrichTransactionsRequestInner(string content, string countryCode)
        {
            Content = content;
            CountryCode = countryCode;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Content is the payment description, maximum 128 characters.
        /// </summary>
        /// <value>Content is the payment description, maximum 128 characters.</value>
        /* <example>COSTA PICKUP LONDON</example> */
        [JsonPropertyName("content")]
        public string Content { get; set; }

        /// <summary>
        /// CountryCode is the ISO 3166-1 alpha-2 two-character country code.
        /// </summary>
        /// <value>CountryCode is the ISO 3166-1 alpha-2 two-character country code.</value>
        /* <example>GB</example> */
        [JsonPropertyName("countryCode")]
        public string CountryCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EnrichTransactionsRequestInner {\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  CountryCode: ").Append(CountryCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Content (string) maxLength
            if (this.Content != null && this.Content.Length > 128)
            {
                yield return new ValidationResult("Invalid value for Content, length must be less than 128.", new [] { "Content" });
            }

            // CountryCode (string) maxLength
            if (this.CountryCode != null && this.CountryCode.Length > 2)
            {
                yield return new ValidationResult("Invalid value for CountryCode, length must be less than 2.", new [] { "CountryCode" });
            }

            // CountryCode (string) minLength
            if (this.CountryCode != null && this.CountryCode.Length < 2)
            {
                yield return new ValidationResult("Invalid value for CountryCode, length must be greater than 2.", new [] { "CountryCode" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EnrichTransactionsRequestInner" />
    /// </summary>
    public partial class EnrichTransactionsRequestInnerJsonConverter : JsonConverter<EnrichTransactionsRequestInner>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="EnrichTransactionsRequestInnerJsonConverter" /> class.
        /// </summary>
        public EnrichTransactionsRequestInnerJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="EnrichTransactionsRequestInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EnrichTransactionsRequestInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> content = default;
            Option<string?> countryCode = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "content":
                            content = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "countryCode":
                            countryCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!content.IsSet)
                throw new ArgumentException("Property is required for class EnrichTransactionsRequestInner.", nameof(content));

            if (!countryCode.IsSet)
                throw new ArgumentException("Property is required for class EnrichTransactionsRequestInner.", nameof(countryCode));

            if (content.IsSet && content.Value == null)
                throw new ArgumentNullException(nameof(content), "Property is not nullable for class EnrichTransactionsRequestInner.");

            if (countryCode.IsSet && countryCode.Value == null)
                throw new ArgumentNullException(nameof(countryCode), "Property is not nullable for class EnrichTransactionsRequestInner.");

            return new EnrichTransactionsRequestInner(content.Value!, countryCode.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="EnrichTransactionsRequestInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="enrichTransactionsRequestInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EnrichTransactionsRequestInner enrichTransactionsRequestInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, enrichTransactionsRequestInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EnrichTransactionsRequestInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="enrichTransactionsRequestInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EnrichTransactionsRequestInner enrichTransactionsRequestInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (enrichTransactionsRequestInner.Content == null)
                throw new ArgumentNullException(nameof(enrichTransactionsRequestInner.Content), "Property is required for class EnrichTransactionsRequestInner.");

            if (enrichTransactionsRequestInner.CountryCode == null)
                throw new ArgumentNullException(nameof(enrichTransactionsRequestInner.CountryCode), "Property is required for class EnrichTransactionsRequestInner.");

            writer.WriteString("content", enrichTransactionsRequestInner.Content);

            writer.WriteString("countryCode", enrichTransactionsRequestInner.CountryCode);
        }
    }
}
