// <auto-generated>
/*
 * XYO RESTful Transaction Enrichment API
 *
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Xyo.Generated.Client;

namespace Xyo.Generated.Model
{
    /// <summary>
    /// EnrichmentResponse
    /// </summary>
    public partial class EnrichmentResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EnrichmentResponse" /> class.
        /// </summary>
        /// <param name="merchant">Merchant is the name of the merchant.</param>
        /// <param name="description">Description is a brief description of the merchant.</param>
        /// <param name="categories">Categories lists categories fitting the description of the merchant.</param>
        /// <param name="logo">Logo is a base64-encoded PNG or JPEG representing the merchant logo.</param>
        /// <param name="location">Location describes the country and city. May be empty if the API returns null.</param>
        /// <param name="address">Address describes the exact address of purchase. May be empty if the API returns null.</param>
        [JsonConstructor]
        public EnrichmentResponse(string merchant, string description, List<string> categories, string logo, string location, string address)
        {
            Merchant = merchant;
            Description = description;
            Categories = categories;
            Logo = logo;
            Location = location;
            Address = address;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Merchant is the name of the merchant.
        /// </summary>
        /// <value>Merchant is the name of the merchant.</value>
        /* <example>Costa Coffee</example> */
        [JsonPropertyName("merchant")]
        public string Merchant { get; set; }

        /// <summary>
        /// Description is a brief description of the merchant.
        /// </summary>
        /// <value>Description is a brief description of the merchant.</value>
        /* <example>Costa Coffee is a British coffeehouse chain and a subsidiary of The Coca-Cola Company.</example> */
        [JsonPropertyName("description")]
        public string Description { get; set; }

        /// <summary>
        /// Categories lists categories fitting the description of the merchant.
        /// </summary>
        /// <value>Categories lists categories fitting the description of the merchant.</value>
        /* <example>[&quot;Food &amp; Beverage&quot;,&quot;Cafes &amp; Coffee Shops&quot;,&quot;Dining Out&quot;]</example> */
        [JsonPropertyName("categories")]
        public List<string> Categories { get; set; }

        /// <summary>
        /// Logo is a base64-encoded PNG or JPEG representing the merchant logo.
        /// </summary>
        /// <value>Logo is a base64-encoded PNG or JPEG representing the merchant logo.</value>
        /* <example>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg&#x3D;&#x3D;</example> */
        [JsonPropertyName("logo")]
        public string Logo { get; set; }

        /// <summary>
        /// Location describes the country and city. May be empty if the API returns null.
        /// </summary>
        /// <value>Location describes the country and city. May be empty if the API returns null.</value>
        /* <example>United Kingdom, London</example> */
        [JsonPropertyName("location")]
        public string Location { get; set; }

        /// <summary>
        /// Address describes the exact address of purchase. May be empty if the API returns null.
        /// </summary>
        /// <value>Address describes the exact address of purchase. May be empty if the API returns null.</value>
        /* <example>40-42 Great Portland St, London W1W 7LZ</example> */
        [JsonPropertyName("address")]
        public string Address { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EnrichmentResponse {\n");
            sb.Append("  Merchant: ").Append(Merchant).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Categories: ").Append(Categories).Append("\n");
            sb.Append("  Logo: ").Append(Logo).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EnrichmentResponse" />
    /// </summary>
    public partial class EnrichmentResponseJsonConverter : JsonConverter<EnrichmentResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="EnrichmentResponseJsonConverter" /> class.
        /// </summary>
        public EnrichmentResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="EnrichmentResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EnrichmentResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> merchant = default;
            Option<string?> description = default;
            Option<List<string>?> categories = default;
            Option<string?> logo = default;
            Option<string?> location = default;
            Option<string?> address = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "merchant":
                            merchant = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "categories":
                            categories = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "logo":
                            logo = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "location":
                            location = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "address":
                            address = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!merchant.IsSet)
                throw new ArgumentException("Property is required for class EnrichmentResponse.", nameof(merchant));

            if (!description.IsSet)
                throw new ArgumentException("Property is required for class EnrichmentResponse.", nameof(description));

            if (!categories.IsSet)
                throw new ArgumentException("Property is required for class EnrichmentResponse.", nameof(categories));

            if (!logo.IsSet)
                throw new ArgumentException("Property is required for class EnrichmentResponse.", nameof(logo));

            if (!location.IsSet)
                throw new ArgumentException("Property is required for class EnrichmentResponse.", nameof(location));

            if (!address.IsSet)
                throw new ArgumentException("Property is required for class EnrichmentResponse.", nameof(address));

            if (merchant.IsSet && merchant.Value == null)
                throw new ArgumentNullException(nameof(merchant), "Property is not nullable for class EnrichmentResponse.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class EnrichmentResponse.");

            if (categories.IsSet && categories.Value == null)
                throw new ArgumentNullException(nameof(categories), "Property is not nullable for class EnrichmentResponse.");

            if (logo.IsSet && logo.Value == null)
                throw new ArgumentNullException(nameof(logo), "Property is not nullable for class EnrichmentResponse.");

            if (location.IsSet && location.Value == null)
                throw new ArgumentNullException(nameof(location), "Property is not nullable for class EnrichmentResponse.");

            if (address.IsSet && address.Value == null)
                throw new ArgumentNullException(nameof(address), "Property is not nullable for class EnrichmentResponse.");

            return new EnrichmentResponse(merchant.Value!, description.Value!, categories.Value!, logo.Value!, location.Value!, address.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="EnrichmentResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="enrichmentResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EnrichmentResponse enrichmentResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, enrichmentResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EnrichmentResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="enrichmentResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EnrichmentResponse enrichmentResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (enrichmentResponse.Merchant == null)
                throw new ArgumentNullException(nameof(enrichmentResponse.Merchant), "Property is required for class EnrichmentResponse.");

            if (enrichmentResponse.Description == null)
                throw new ArgumentNullException(nameof(enrichmentResponse.Description), "Property is required for class EnrichmentResponse.");

            if (enrichmentResponse.Categories == null)
                throw new ArgumentNullException(nameof(enrichmentResponse.Categories), "Property is required for class EnrichmentResponse.");

            if (enrichmentResponse.Logo == null)
                throw new ArgumentNullException(nameof(enrichmentResponse.Logo), "Property is required for class EnrichmentResponse.");

            if (enrichmentResponse.Location == null)
                throw new ArgumentNullException(nameof(enrichmentResponse.Location), "Property is required for class EnrichmentResponse.");

            if (enrichmentResponse.Address == null)
                throw new ArgumentNullException(nameof(enrichmentResponse.Address), "Property is required for class EnrichmentResponse.");

            writer.WriteString("merchant", enrichmentResponse.Merchant);

            writer.WriteString("description", enrichmentResponse.Description);

            writer.WritePropertyName("categories");
            JsonSerializer.Serialize(writer, enrichmentResponse.Categories, jsonSerializerOptions);
            writer.WriteString("logo", enrichmentResponse.Logo);

            writer.WriteString("location", enrichmentResponse.Location);

            writer.WriteString("address", enrichmentResponse.Address);
        }
    }
}
